// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qypjnzmniwengzzpghgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cGpuem1uaXdlbmd6enBnaGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjMyNzksImV4cCI6MjA2MzczOTI3OX0.VenmzaRDgPiqjmazVH1thii2_cGpACJEiCIxXnbwxZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);